Практична робота №1 

Авдєєва Серафима ФІТ 4-4

Варіант 1

In [259]:
import numpy as np

Завдання 1.

1.	Створіть одновимірний масив (вектор) з останніми 10-ма натуральними числами та виведіть його значення


In [260]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


Завдання 2

1.	Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значенн.


In [261]:
a = np.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Завдання 3

1.	Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 100 та виведіть його значення


In [262]:
a = np.random.randint(1, 101, (4,4))
print(a)

[[ 9 80 92 86]
 [ 9 93  9 87]
 [83 86 54  5]
 [49 40 48 24]]


Завдання 4

1.	Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значенн.


In [263]:
a = np.random.rand(3, 3)
print(a)

[[0.49456557 0.55970033 0.11320198]
 [0.13279784 0.20395217 0.13011776]
 [0.92278543 0.99063585 0.50333932]]


Завдання 5

1.	Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [264]:
a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [19 15  8 11  1  1]
b =  [16  3 20  2 11 13]
a + b =  [35 18 28 13 12 14]
a - b =  [  3  12 -12   9 -10 -12]
a * b =  [304  45 160  22  11  13]


Завдання 6

1.	Створіть два вектори розміром 5, заповніть їх довільними цілими числами та знайдіть їх скалярний добуто.


In [265]:
a = np.random.randint(1, 21, size=5)
b = np.random.randint(1, 21, size=5)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [15 19  6 18 18]
b =  [ 9 10 14  5 15]
Скалярний добуток векторів дорівнює: 769


Завдання 7

1.	Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та перемножте їх між собо.


In [266]:
a = np.random.randint(1, 21, size=(3, 2))
b = np.random.randint(1, 21, size=(2, 4))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[20  9]
 [17  9]
 [15 18]]
b =  [[ 6 17 14  2]
 [10 10 20  3]]
Результат множення матриць:
[[210 430 460  67]
 [192 379 418  61]
 [270 435 570  84]]


Завдання 8

1.	Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю


In [267]:
a = np.random.randint(1, 8, size=(2, 2))
print("Вихідна матриця:")
print(a)

if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)

Вихідна матриця:
[[2 3]
 [1 3]]
Обернена матриця:
[[ 1.         -1.        ]
 [-0.33333333  0.66666667]]


Завдання 9.

1.	Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте ї.


In [268]:
a = np.random.rand(3, 3)
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[0.53542513 0.37269604 0.79699138]
 [0.93273971 0.63582186 0.97595251]
 [0.7105137  0.6365941  0.6251778 ]]
Транспонована матриця:
[[0.53542513 0.93273971 0.7105137 ]
 [0.37269604 0.63582186 0.6365941 ]
 [0.79699138 0.97595251 0.6251778 ]]


Завдання 10

1.	Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів отриманого вектору.


In [269]:
matr = np.random.randint(1, 11, size=(3, 4))
vect = np.random.randint(1, 11, size=4)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

sum = np.sum(vect)
print("Сума елементів вектора")
print(sum)

Матриця:
[[ 7  7  3  5]
 [ 6  8  9 10]
 [10  6  6  2]]
Вектор:
[ 2 10  1  7]
Сума елементів вектора
20


Завдання 11

1.	Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на векто.


In [270]:
matr = np.random.randint(1, 11, size=(2, 3))
vect = np.random.randint(1, 11, size=3)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[10  5  9]
 [ 8  8  7]]
Вектор:
[9 4 4]
Результат множення матриці на вектор:
[146 132]


Завдання 12

1.	Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню сум.


In [271]:
a = np.random.randint(1, 11, size=(2,2))
b = np.random.randint(1, 11, size=(2,2))
print("Матриця a:")
print(a)
print("Матриця b:")
print(b)
sum = a+b
print("Сума матриць:")
print(sum)

Матриця a:
[[8 6]
 [1 2]]
Матриця b:
[[ 7  9]
 [10  4]]
Сума матриць:
[[15 15]
 [11  6]]


Завдання 13

1.	Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть їх добуток


In [272]:
a = np.random.rand(2, 2)
b = np.random.rand(2, 2)
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Добуток матриць:")
result = np.dot(a, b)
print(result)

Перша матриця:
[[0.20754703 0.60217256]
 [0.67979957 0.14575847]]
Друга матриця:
[[0.16852976 0.28065255]
 [0.36633799 0.28836375]]
Добуток матриць:
[[0.25557654 0.23189334]
 [0.16796332 0.23281894]]


Завдання 14

1.	Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму елементів матриці.


In [273]:
a = np.random.rand(5, 5)
sum_a = np.sum(a)
print("Матриця")
print(a)
print("Сума елементів матриці:")
print(sum_a)

Матриця
[[0.01431611 0.73441811 0.76044719 0.12509583 0.4259529 ]
 [0.59866966 0.73538254 0.03143386 0.45713377 0.1296727 ]
 [0.56603772 0.82415872 0.42191809 0.94904842 0.31271093]
 [0.17166994 0.9316155  0.7918736  0.31830244 0.64440618]
 [0.63441773 0.81735034 0.75029178 0.24193481 0.75442045]]
Сума елементів матриці:
13.142679316755743


Завдання 15

1.	Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.


In [274]:
a = np.random.randint(-100000000, +100000000, (3,3))/100000000
print("Матриця:")
print(a)

row_sums = a.sum(axis=1)

col_vec = row_sums.reshape((-1, 1))

print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(col_vec)

Матриця:
[[ 0.57162953 -0.15138218  0.34541872]
 [ 0.34719258  0.38636566  0.43679166]
 [ 0.16259817 -0.99862922  0.45537756]]
Вектор-стовпчик з сумами елементів кожного рядка:
[[ 0.76566607]
 [ 1.1703499 ]
 [-0.38065349]]


Висновок: у даній практичній роботі я виконувала різноманітні операції з матрицями та векторами, такі як додавання, множення, віднімання, заповнення випадковими числами, знаходження суми елементів, транспонування тощо, з використанням пакета NumPy.